<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BarcodeScanning.Native.Maui" Version="3.1.0" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="15.0.0" />
    <PackageVersion Include="CommunityToolkit.Maui.Core" Version="15.0.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Duende.IdentityModel.OidcClient" Version="7.1.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.90" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.90" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="Polly" Version="8.7.0" />
    <PackageVersion Include="Refit" Version="15.0.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="ZXing.Net.Maui" Version="0.10.4" />
    <PackageVersion Include="ZXing.Net.Maui.Controls" Version="0.10.4" />
  </ItemGroup>
</Project>