name: continuous

on:
  push:
    branches:
      - 'feat/**'

env:
  DOTNETVERSION: 7.0.x
  PROJECT_PATH: "src/Pantry.Mobile/Pantry.Mobile.csproj"

jobs:
  # ************************* #
  # >>>>>>> iOS Build <<<<<<< #
  # ************************* #
  maui-ios:
    runs-on: [self-hosted, macOS, ARM64]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        shell: bash
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 -D -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 -D -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Restore NuGet packages
        shell: bash
        run: dotnet restore ${{ env.PROJECT_PATH }} --runtime ios-arm64

      # https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview
      - name: Build MAUI iOS project
        env:
          NEW_VERSION: ${{ github.run_number }}
        shell: bash
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -f net7.0-ios --no-restore /p:ApplicationVersion=${{ env.NEW_VERSION }} /p:packageApp=false

      - name: Publish MAUI iOS project
        env:
          NEW_VERSION: ${{ github.run_number }}
        shell: bash
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -f net7.0-ios --no-restore -o app/publish /p:ApplicationVersion=${{ env.NEW_VERSION }} /p:ArchiveOnBuild=false /p:packageApp=true

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-ios
          path: app/publish/Pantry.Mobile.ipa
          retention-days: 5
