---
name: Markdownlint
on:
  pull_request:
  merge_group:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Markdownlint
        uses: reviewdog/action-markdownlint@3ada8babcda166021650568fe477cda59c7266bf # v0.28.1
        with:
          level: "error"
          filter_mode: "nofilter"
