---
name: Markdownlint
on:
  pull_request:
  merge_group:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Markdownlint
        uses: reviewdog/action-markdownlint@d6b1ab6a31042054e7848e23358ef7d5e2cc9764 # v0.31.3
        with:
          level: "error"
          filter_mode: "nofilter"
