name: pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

env:
  DOTNETVERSION: 7.0.x
  PROJECT_PATH: "src/Pantry.Mobile/Pantry.Mobile.csproj"

jobs:
  maui-build:
    runs-on: windows-2022
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "${{env.DOTNETVERSION}}"

      - name: Install .NET MAUI
        shell: pwsh
        run: dotnet workload install maui-android maui-ios --source https://api.nuget.org/v3/index.json

      - name: Restore NuGet packages
        shell: pwsh
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        shell: pwsh
        run: dotnet build ${{ env.PROJECT_PATH }}

      # - name: Build and Run UnitTests
      # shell: pwsh
      # run: |
      # dotnet build <path to unit test csproj>
      # dotnet test <path to unit test csproj> --no-build --verbosity normal
