name: pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

env:
  PROJECT_PATH: "src/Pantry.Mobile/Pantry.Mobile.csproj"
  TEST_PROJECT_PATH: "tests/Pantry.Mobile.Tests.Core/Pantry.Mobile.Tests.Core.csproj"

jobs:
  maui-build:
    runs-on: windows-2025
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Install .NET MAUI
        shell: pwsh
        run: dotnet workload install maui-android maui-ios --source https://api.nuget.org/v3/index.json

      - name: Restore NuGet packages
        shell: pwsh
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        shell: pwsh
        run: dotnet build ${{ env.PROJECT_PATH }}

      - name: Build and Run UnitTests
        shell: pwsh
        run: |
          dotnet build ${{ env.TEST_PROJECT_PATH }}
          dotnet test ${{ env.TEST_PROJECT_PATH }} --no-build --verbosity normal --logger trx

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          retention-days: 5
          path: tests/**/TestResults/*
