name: Test Report

on:
  workflow_run:
    workflows: ['pull request']
    types:
      - completed

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/test-reporter@v2.1.0
      with:
        name: Generate Report
        artifact: test-results
        path: '**/*.trx'
        reporter: dotnet-trx
        token: ${{ github.token }}
