---
name: Test Report

on:
  workflow_run:
    workflows: ["pull request"]
    types:
      - completed

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dorny/test-reporter@d1b5dff021aa968b288b02285a8bf47471c5928a # v3.2.0
        with:
          name: Generate Report
          artifact: test-results
          path: "**/*.trx"
          reporter: dotnet-trx
          token: ${{ github.token }}
