name: Test Report

on:
  workflow_run:
    workflows: ['pull request']
    types:
      - completed

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        artifact: test-results
        name: Workflow Report
        path: '**/*.trx'
        reporter: dotnet-trx
